name: dsbuild
description: Dataset preparation for LM training. Usable as a standalone tool and a library. Process conversations using StreamTransformers configured with simple YAML. Supports multithreading.
version: 0.1.0-alpha.4
repository: https://github.com/Justin42/dsbuild
topics: [ ai, nlp, lm ]

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  async: ^2.11.0
  bloc: ^8.1.1
  crypto: ^3.0.3
  csv: ^5.0.2
  fast_immutable_collections: ^9.1.3
  glob: ^2.1.2
  html: ^0.15.3
  http: ^1.0.0
  logging: ^1.1.1
  meta: ^1.9.1
  path: ^1.8.3
  yaml: ^3.1.2

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0

executables:
  dsbuild:
